<a href="https://colab.research.google.com/github/Student-Anshuman/DataScience_Learning/blob/main/KBinsDiscretizer_%26_Binning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# code
# Importing Libraries
from sklearn.preprocessing import KBinsDiscretizer
import numpy as np

# Creating a mock data
data = np.array([[1, 3, 5], [2, 7, 9], [4, 6, 8]])

# Initializing and setting the parameters n_bins to 3, encode to ordinal and strategy to uniform
discretizer = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')

# Fitting and transforming the data into n_bins number of bins
binned_data = discretizer.fit_transform(data)

# Printing binned data to check the change
print(binned_data)
data

[[0. 0. 0.]
 [3. 9. 9.]
 [9. 7. 7.]]


array([[1, 3, 5],
       [2, 7, 9],
       [4, 6, 8]])